[package]
name = "nodem-ffi"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
nodem-rs = { git = "https://github.com/saschaklick/nodem-rs", features = ["base", "alloc", "runtime"] }
embedded-alloc = "0.6"
critical-section = { version = "1.2", features = ["restore-state-u32"] }
log = "0.4"

[patch."https://github.com/saschaklick/virtmach-rs"]
virtmach = { path = "../../virtmach-rs" }

[profile.release]
debug = 2
